name: MO Wiki Build

permissions:
  contents: write

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  ubuntu_build:
    name: Building Mk-Docs on latest Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Build static web files
        run: python3 -m mkdocs build

      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: site
          token: ${{secrets.XK2013_GITHUB_TOKEN}}